// <auto-generated />
using ASN.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASN.Infrastructure.Migrations
{
    [DbContext(typeof(AsnContext))]
    partial class AsnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ASN.Infrastructure.Data.Models.BoxHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ASN.Infrastructure.Data.Models.BoxLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxHeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoxHeaderId");

                    b.ToTable("Matchups");
                });

            modelBuilder.Entity("ASN.Infrastructure.Data.Models.BoxLine", b =>
                {
                    b.HasOne("ASN.Infrastructure.Data.Models.BoxHeader", "header")
                        .WithMany("BoxLines")
                        .HasForeignKey("BoxHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("header");
                });

            modelBuilder.Entity("ASN.Infrastructure.Data.Models.BoxHeader", b =>
                {
                    b.Navigation("BoxLines");
                });
#pragma warning restore 612, 618
        }
    }
}
